# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sukinull/Build/project_basex/project_basex.cache/wt [current_project]
set_property parent.project_path /home/sukinull/Build/project_basex/project_basex.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
add_files /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_blk_mem_gen_0_0/base_zynq_design_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_bram_ctrl_0_0/base_zynq_design_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_pc_1/base_zynq_design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/base_zynq_design_ooc.xdc]
set_property is_locked true [get_files /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd]

read_vhdl -library xil_defaultlib /home/sukinull/Build/project_basex/project_basex.srcs/sources_1/bd/base_zynq_design/hdl/base_zynq_design_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file base_zynq_design_wrapper.hwdef }
synth_design -top base_zynq_design_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef base_zynq_design_wrapper.dcp
catch { report_utilization -file base_zynq_design_wrapper_utilization_synth.rpt -pb base_zynq_design_wrapper_utilization_synth.pb }
